version: '3.1'

services:
  app:
    container_name: "vabanque-app"
    build: .
    ports:
      - "80:8080"

  mysql:
    container_name: "vabanque-mysql"
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:5"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "zaq1@WSX"

  adminer:
    container_name: "vabanque-adminer"
    image: "adminer"
    ports:
      - "3310:8080"
