version: '3.1'

services:

  mysql:
    container_name: "vabanque-mysql"
    command: --default-authentication-plugin=mysql_native_password
    image: "mysql:8"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "zaq1@WSX"

  adminer:
    container_name: "vabanque-adminer"
    image: "adminer"
    ports:
      - "3310:8080"
