version: '3.1'

services:

  db:
    container_name: "vabanque-postgres"
    image: "postgres:11"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "zaq1@WSX"

  adminer:
    container_name: "vabanque-adminer"
    image: "adminer"
    ports:
      - "5435:8080"
