spring:
  datasource:
    url: jdbc:mysql://localhost:3308/vabanque
    username: root
    password: zaq1@WSX
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: verify
#    show-sql: true
  servlet.multipart:
    file-size-threshold: 2KB
    max-file-size: 5MB
    max-request-size: 10MB

vabanque.jwt:
  secret: vabanquesecret
  expiration: 300000
