spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3308/vabanque}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:zaq1@WSX}
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: verify
#    show-sql: true
  servlet.multipart:
    file-size-threshold: 2KB
    max-file-size: 5MB
    max-request-size: 10MB

vabanque.jwt:
  secret: ${JWT_SECRET:vabanquesecret}
  expiration: 300000
